---

keys:
  - &admin_andrew D87BD9DCF11BACD6CDB40CB213732FB13E61E0BE
  - &server_eternia age190ap7t3z5pvntgypd64zanz9anzmpna7fksusuajnedwzewfkqlqum4ncz
  - &server_sparrow age13ga3v53gnhw0sk5506yl25xzgjmqjlrkc5f8hyw2teyz40p6sdvqx47kya
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - pgp:
      - *admin_andrew
      age:
      - *server_eternia
      - *server_sparrow
